// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b477641b-30ac-4b6a-8b84-c0390c71840a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zNCoccXW7",
    "aws_user_pools_web_client_id": "3e7td0gkv423v82nm3q1m6q7oa",
    "oauth": {
        "domain": "teamtaskse8f69cbc-e8f69cbc-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://dev.d1qdacfrb816as.amplifyapp.com/",
        "redirectSignOut": "https://dev.d1qdacfrb816as.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://6ovlabnq3rh2lo6cqqjiiqgvga.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "teamtasks-20190831133716-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1ah3q7rd84wze.cloudfront.net"
};


export default awsmobile;
